name: API Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: yards
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Add sqlx for Migrations
      run: cargo install sqlx-cli --no-default-features --features rustls,postgres
    - name: Run Migrations
      working-directory: ./yards-api
      env:
        - DATABASE_URL=postgres://postgres:postgres@postgres/yards
      run: sqlx migrate run
    - name: Build
      working-directory: ./yards-api
      env:
        - DATABASE_URL=postgres://postgres:postgres@postgres/yards
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./yards-api
      run: cargo test --verbose
