name: Frontend Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        working-directory: ./yards-api
        run: cargo clippy --all-targets --all-features -- -D warnings
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./yards-frontend
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./yards-frontend
      run: cargo test --verbose
